// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBw8q_WTLbT1Ya641xvk58Jvsakp8rpg',
    appId: '1:489643015209:android:3e0a95c0c411262bd03038',
    messagingSenderId: '489643015209',
    projectId: 'goodnotes-firstfluttergo',
    databaseURL: 'https://goodnotes-firstfluttergo-default-rtdb.firebaseio.com',
    storageBucket: 'goodnotes-firstfluttergo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKWRgy6te_vT0AOCNvdbPzxz6RE2OlKGY',
    appId: '1:489643015209:ios:d2efb726a4a9e146d03038',
    messagingSenderId: '489643015209',
    projectId: 'goodnotes-firstfluttergo',
    databaseURL: 'https://goodnotes-firstfluttergo-default-rtdb.firebaseio.com',
    storageBucket: 'goodnotes-firstfluttergo.appspot.com',
    iosBundleId: 'com.firstfluttergo.firstfluttergo',
  );
}